require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/**/*.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/**/*.rb'
    - 'config/initializers/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/views/**/*'
  SkipBlocks: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/models/seeds_spec.rb'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/system/**/*'
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 5

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
   Max: 6

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
