version: "3.7"
services:
  app: &app
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/app
      - ./config/database.docker.yml:/app/config/database.yml:ro
      - ~/.composer/docker-cache/:/root/.composer
      # - ./tmp/fonts/mova:/app/app/webpacker/fonts/mova:ro
    ports:
      - "3000:3000"
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/rails", "s", "-b", "0.0.0.0"]
    environment:
      APP_HOST: "app:3000"
      E2E_SERVER_PORT: "3001"
      E2E_APP_HOST: "app.local:3001"
      SELENIUM_HOST: "selenium:4444"
      CAMP_START: ${CAMP_START}
      CAMP_END: ${CAMP_END}
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      APP_BASE_URL: http://orca.localhost:3000
      MEMCACHE_SERVERS: memcached
      SECRET_KEY_BASE: "secret"
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_CLIENT_SECRET_KEY: ${OIDC_CLIENT_SECRET_KEY}
      MIDATA_BASE_URL: ${MIDATA_BASE_URL}
      MIDATA_USER_EMAIL: ${MIDATA_USER_EMAIL}
      MIDATA_USER_TOKEN: ${MIDATA_USER_TOKEN}
      LIMESURVEY_USERNAME: ${LIMESURVEY_USERNAME}
      LIMESURVEY_PASSWORD: ${LIMESURVEY_PASSWORD}
      LIMESURVEY_SURVEY_ID: ${LIMESURVEY_SURVEY_ID}
      VIRTUAL_HOST: ${DOMAIN}
      DEVISE_PEPPER: "rake secret"
      DEVISE_SECRET_KEY: "rake secret"
      ROOT_CAMP_UNIT_ID_WOLF: 1328
      ROOT_CAMP_UNIT_ID_PFADI: 1329
      ROOT_CAMP_UNIT_ID_PIO: 1328
      ROOT_CAMP_UNIT_ID_PTA: 1328
      SMTP_HOST: mail
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: 25
      SMTP_AUTH: ${SMTP_AUTH:-plain}
      FEATURES: "unit_activity_booking"
      VISITOR_DAY_ACTIVITY_ID: 1
    depends_on:
      - db
      - mail
      - memcached
      - webpack
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"

  webpack:
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    entrypoint: [".docker/entrypoints/webpack.sh"]
    command: ["bin/webpacker-dev-server"]
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      NODE_PATH: /app/node_modules
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    restart: on-failure

  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    networks:
      selenium:

  db:
    image: postgres:11-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: orca_e2e
      POSTGRES_PASSWORD: postgres

  mail:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"

  memcached:
    image: memcached:1.5-alpine
    command: [memcached, -l, "0.0.0.0", -p, "11211"]

volumes:
  db_data:

networks:
  selenium:
