version: '3.7'
services:

  db:
    image: postgres
    container_name: orca_postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - orca_db

  app:
    build: .
    image: mova21-orca:latest
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: production
      MEMCACHE_SERVERS: memcached
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_CLIENT_SECRET_KEY: ${OIDC_CLIENT_SECRET_KEY}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DEVISE_PEPPER: ${DEVISE_PEPPER}
      DEVISE_SECRET_KEY: ${DEVISE_SECRET_KEY}
      MIDATA_BASE_URL: ${MIDATA_BASE_URL}
      MIDATA_USER_EMAIL: ${MIDATA_USER_EMAIL}
      MIDATA_USER_TOKEN: ${MIDATA_USER_TOKEN}
      ROOT_CAMP_UNIT_ID_WOLF: ${ROOT_CAMP_UNIT_ID_WOLF}
      ROOT_CAMP_UNIT_ID_PFADI: ${ROOT_CAMP_UNIT_ID_PFADI}
      ROOT_CAMP_UNIT_ID_PIO: ${ROOT_CAMP_UNIT_ID_PIO}
      ROOT_CAMP_UNIT_ID_PTA: ${ROOT_CAMP_UNIT_ID_PIO}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTH: {SMTOP_AUTH:-plain}
    depends_on:
      - db
      - memcached
    networks:
      - orca_db
      - proxy_net

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

networks:
  orca_db:
  proxy_net:
    external:
      name: proxy_net
