version: "3.7"
services:
  app:
    image: mova21-orca:latest
    container_name: orca
    build:
      context: .
      target: production
    user: "0:0"
    environment:
      CAMP_START: ${CAMP_START}
      CAMP_END: ${CAMP_END}
      SEND_PROGRAM_CHANGE_LOG_NOTIFICATIONS: "true"
      APP_BASE_URL: ${APP_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: production
      MEMCACHE_SERVERS: memcached
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_CLIENT_SECRET_KEY: ${OIDC_CLIENT_SECRET_KEY}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DEVISE_PEPPER: ${DEVISE_PEPPER}
      DEVISE_SECRET_KEY: ${DEVISE_SECRET_KEY}
      MIDATA_BASE_URL: ${MIDATA_BASE_URL}
      MIDATA_USER_EMAIL: ${MIDATA_USER_EMAIL}
      MIDATA_USER_TOKEN: ${MIDATA_USER_TOKEN}
      MIDATA_OAUTH_ACCESS_TOKEN: ${MIDATA_OAUTH_ACCESS_TOKEN}
      LIMESURVEY_USERNAME: ${LIMESURVEY_USERNAME}
      LIMESURVEY_PASSWORD: ${LIMESURVEY_PASSWORD}
      LIMESURVEY_SURVEY_ID: ${LIMESURVEY_SURVEY_ID}
      ROOT_CAMP_UNIT_ID_WOLF: 11402
      ROOT_CAMP_UNIT_ID_PFADI: 11405
      ROOT_CAMP_UNIT_ID_PIO: 11404
      ROOT_CAMP_UNIT_ID_PTA: 11406
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTH: "login"
      RAILS_SERVE_STATIC_FILES: "on"
      STORAGE_SERVICE: ${STORAGE_SERVICE}
      STORAGE_ACCOUNT_NAME: ${STORAGE_ACCOUNT_NAME}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_CONTAINER: ${STORAGE_CONTAINER}
      VISITOR_DAY_ACTIVITY_ID: ${VISITOR_DAY_ACTIVITY_ID:-223}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
    tty: true
    stdin_open: true
    entrypoint: ["/entrypoint"]

  redis:
    image: redis:6
