version: '3.5'
services:

  app:
    build:
      context: .
      target: development
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle/
    ports:
      - '3000:3000'
    environment:
      APP_BASE_URL: http://orca.localhost:3000
      DATABASE_URL: postgresql://postgres@db/orca_development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
      MEMCACHE_SERVERS: memcached
      SECRET_KEY_BASE: 'secret'
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_CLIENT_SECRET_KEY: ${OIDC_CLIENT_SECRET_KEY}
      MIDATA_BASE_URL: ${MIDATA_BASE_URL}
      MIDATA_USER_EMAIL: ${MIDATA_USER_EMAIL}
      MIDATA_USER_TOKEN: ${MIDATA_USER_TOKEN}
      LIMESURVEY_USERNAME: ${LIMESURVEY_USERNAME}
      LIMESURVEY_PASSWORD: ${LIMESURVEY_PASSWORD}
      LIMESURVEY_SURVEY_ID: ${LIMESURVEY_SURVEY_ID}
      VIRTUAL_HOST: ${DOMAIN}
      DEVISE_PEPPER: 'rake secret'
      DEVISE_SECRET_KEY: 'rake secret'
      ROOT_CAMP_UNIT_ID_WOLF: 1328
      ROOT_CAMP_UNIT_ID_PFADI: 1328
      ROOT_CAMP_UNIT_ID_PIO: 1328
      ROOT_CAMP_UNIT_ID_PTA: 1328
    depends_on:
      - db
      - webpack
      - mail
      - memcached
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: orca_test

  webpack:
    build:
      context: .
      target: development
    command: ["bin/webpack-dev-server"]
    entrypoint: [".docker/entrypoints/webpack.sh"]
    volumes:
      - .:/app
      - webpack_node_modules:/app/node_modules
      - webpack_bundle:/usr/local/bundle/
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  test:
    build:
      context: .
      target: development
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/check"]
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_bundle:/usr/local/bundle/
    environment:
      APP_HOST: test
      PORT: 3000
      DATABASE_URL: postgresql://postgres@db/orca_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RAILS_ENV: test
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      MIDATA_BASE_URL: ${MIDATA_BASE_URL}
      MIDATA_USER_EMAIL: ${MIDATA_USER_EMAIL}
      MIDATA_USER_TOKEN: ${MIDATA_USER_TOKEN}
      ROOT_CAMP_UNIT_ID_WOLF: 1328
      ROOT_CAMP_UNIT_ID_PFADI: 1328
      ROOT_CAMP_UNIT_ID_PIO: 1328
      ROOT_CAMP_UNIT_ID_PTA: 1328
    depends_on:
      - db
      - selenium
    networks:
      default:
      selenium:
        aliases:
          - test

  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    networks:
      selenium:
        aliases:
          - app

  production:
    build: .
    image: bulacafe-orca:latest

networks:
  selenium:

volumes:
  app_bundle:
  app_node_modules:
  webpack_bundle:
  webpack_node_modules:
  db_data:
