---
name: Continous Integration - CI

on:
  push:
    branches: [develop-ci]
  pull_request:
    branches: [develop-ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: buildx
        uses: docker/setup-buildx-action@master

      - name: prepare artifacts
        run: mkdir -p artifacts

      - name: docker build test
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          target: build
          tags: e2e_test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: docker build
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: mova21-orca:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: migrate
        run: docker compose --file docker-compose.ci.yml run e2e_target bin/rails db:drop db:create db:migrate

      - name: bin/check
        run: docker compose --file docker-compose.ci.yml run e2e_test bin/check

      - if: failure()
        run: docker compose --file docker-compose.ci.yml logs e2e_test

      - if: failure()
        run: docker compose --file docker-compose.ci.yml logs e2e_target

      - if: failure()
        name: dump log
        run: docker compose --file docker-compose.ci.yml logs > ./artifacts/docker-compose.ci.log

      - if: failure()
        name: dump screenshots
        run: cp -r tmp/capybara ./artifacts/

      - if: failure()
        name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts
